name: flask_database_app
dependencies:
  - python=3.10
  - pip
  - pip:
      - Flask==2.2.3
      - Flask-WTF==1.1.1
      - python-dotenv==1.0.0
      - Flask-SQLAlchemy==3.0.3
      - psycopg2-binary==2.9.5
      - Flask-Migrate==4.0.4