"""Add email column to user_submit

Revision ID: c865cbba3abc
Revises: 
Create Date: 2023-03-18 17:55:21.421560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c865cbba3abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=320), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_submit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
